INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (1, 'US', -5);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (2, 'India', 5.5);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (3, 'Europe', 1);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (4, 'Australia', 10);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (5, 'Canada', -5);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (6, 'Brazil', -3);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (7, 'South Africa', 2);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (8, 'Japan', 9);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (9, 'China', 8);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (10, 'Russia', 3);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (11, 'Mexico', -6);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (12, 'Argentina', -3);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (13, 'United Kingdom', 0);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (14, 'Germany', 1);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (15, 'France', 1);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (16, 'Italy', 1);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (17, 'Spain', 1);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (18, 'Egypt', 2);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (19, 'Singapore', 8);
INSERT INTO TIME_ZONE (id, region, utc_offset) VALUES (20, 'New Zealand', 12);
