spring.application.name=time-converter-service
spring.cloud.config.enabled=false

server.port=8002


logging.level.com.netflix.client=DEBUG
logging.level.org.springframework.cloud.netflix.ribbon=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.com.netflix.loadbalancer=DEBUG
logging.level.com.netflix.discovery=DEBUG


# Ribbon load balancer configuration for Time-Difference-Service
time-difference-service.ribbon.listOfServers=http://localhost:8001,http://localhost:8011

# Disable Eureka discovery for Ribbon demo purposes (optional)
time-difference-service.ribbon.eureka.enabled=false



#eureka server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/